# l{x}c{y}: len(DEPTHS)={x}, NUM_CLUSTERS={y}

MODEL:
  TYPE: gvit
  DROP_PATH_RATE: 0.1
  GVIT:
    EMBED_DIM: 384
    DIM_PER_HEAD: 64
    PATCH_SIZE: 16
    DEPTHS: [3, 3, 3, 3, 3, 3]
    NUM_CLUSTERS: [64, 64, 64, 64, 64, 64]
    EMBED_FACTORS: [1, 1, 1, 1, 1, 1]
    DOWNSAMPLE_TYPES: ['none', 'none', 'none', 'none', 'none']
    NUM_ASSIGN: [-1, -1, -1, -1, -1]
    NUM_HEADS: [0, 0, 0, 0, 0, 0]
    WITH_GAP: true
    ATTN_MASK_STYLE: []
    BOTTLENECK_INDICES: [[2], [2], [2], [2], [2], [2]]
    CONCAT_CLUSTER_TOKEN: true
