# l{x}c{y}: len(DEPTHS)={x}, NUM_CLUSTERS={y}
# bhalfpre: BOTTLENECK_INDICES= [[0,2,4,6,8,10]]

MODEL:
  TYPE: gvit
  DROP_PATH_RATE: 0.1
  GVIT:
    EMBED_DIM: 384
    DIM_PER_HEAD: 64
    PATCH_SIZE: 16
    DEPTHS: [12]
    NUM_CLUSTERS: [64]
    EMBED_FACTORS: [1]
    DOWNSAMPLE_TYPES: []
    NUM_ASSIGN: []
    WITH_GAP: true
    ATTN_MASK_STYLE: []
    BOTTLENECK_INDICES: [[0,2,4,6,8,10]]
