# l{x}c{y}: len(DEPTHS)={x}, NUM_CLUSTERS={y}
# pred-co: PRED_SRC=['cluster']

MODEL:
  TYPE: cvit
  DROP_PATH_RATE: 0.1
  CVIT:
    EMBED_DIM: 768
    DIM_PER_HEAD: 64
    PATCH_SIZE: 16
    DEPTHS: [12]
    NUM_CLUSTERS: [64]
    EMBED_FACTORS: [1]
    DOWNSAMPLE_TYPES: []
    NUM_ASSIGN: []
    WITH_GAP: true
    ATTN_MASK_STYLE: []
    PRED_SRC: ['cluster']
