# l{x}c{y}: len(DEPTHS)={x}, NUM_CLUSTERS={y}

MODEL:
  TYPE: cvit
  DROP_PATH_RATE: 0.1
  CVIT:
    EMBED_DIM: 384
    DIM_PER_HEAD: 64
    PATCH_SIZE: 16
    DEPTHS: [3, 3, 3, 3]
    NUM_CLUSTERS: [32, 16, 8, 0]
    EMBED_FACTORS: [1, 1, 1, 1]
    DOWNSAMPLE_TYPES: ['assign', 'assign', 'assign']
    NUM_ASSIGN: [32, 16, 8]
    WITH_GAP: true
    ATTN_MASK_STYLE: []
    INTER_MODE: copy
