MODEL:
  TYPE: cmvit
  DROP_PATH_RATE: 0.2
  CMVIT:
    EMBED_DIM: 96
    DEPTHS: [1, 1, 10, 1]
    NUM_CLUSTERS: [64, 32, 16, 8]
    NUM_ANCHORS: [64, 16, 4, 1]
    POOL_MODE: unfold
    WITH_GAP: true
