# cmvit-s: DEPTHS=[2, 2, 6, 2]
# cmvit-m: DEPTHS=[1, 1, 10, 1]
# cmvit-v: DEPTHS=[12], DROP_PATH_RATE=0. be default.
# cmvit-base: EMBED_DIM=768, PATCH_SIZE=16, DEPTH=[12], NUM_CLUSTERS=[64]
# c1: NUM_CLUSTERS=[64, 32, 16, 8]
# cN: NUM_CLUSTERS=[64n, 32n, 16n, 8n]
# ppp: POOL_STAGES=[0, 1, 2]
# ppaX: POOL_STAGES=[0, 1], NUM_ASSIGN=[..., ..., X]
# wca: WITH_CLUSTER_ATTN=true
# ctwd: CLUSTER_TOKEN_WD=true

MODEL:
  TYPE: cmvit
  DROP_PATH_RATE: 0.
  CMVIT:
    EMBED_DIM: 96
    PATCH_SIZE: 4
    DEPTHS: [1, 1, 10, 1]
    NUM_CLUSTERS: [512, 256, 128, 64]
#    DEPTHS: [2, 2, 6, 2]
#    NUM_CLUSTERS: [512, 256, 128, 1]
    POOL_STAGES: [0]
    NUM_ASSIGN: [-1, 32, 8]
    INTER_MODE: linear
    ASSIGN_TYPE: ['gumbel', 'hard', 'inv'] # norm w.o. skip: 10, norm w. skip: 10
    WITH_CLUSTER_ATTN: false
    POOL_MODE: conv
    WITH_GAP: true
    CLUSTER_TOKEN_WD: true
    I2C_SHARE_ATTN: true
TRAIN:
  CLIP_MODE: agc
  CLIP_GRAD: 0.1
