# cmvit-s: DEPTHS=[2, 2, 6, 2]
# cmvit-m: DEPTHS=[1, 1, 10, 1]
# c1: NUM_CLUSTERS=[64, 32, 16, 8]
# cN: NUM_CLUSTERS=[64n, 32n, 16n, 8n]
# ppp: POOL_STAGES=[0, 1, 2]
# ppaX: POOL_STAGES=[0, 1], NUM_ASSIGN=[..., ..., X]
# wca: WITH_CLUSTER_ATTN=true

MODEL:
  TYPE: cmvit
  DROP_PATH_RATE: 0.2
  CMVIT:
    EMBED_DIM: 96
#    DEPTHS: [1, 1, 10, 1]
    DEPTHS: [2, 2, 6, 2]
    NUM_CLUSTERS: [512, 256, 128, 64]
#    NUM_CLUSTERS: [64, 32, 16, 8]
    WITH_CLUSTER_ATTN: true
    POOL_STAGES: [0, 1, 2]
    POOL_MODE: unfold
    WITH_GAP: true