# cmvit-s: DEPTHS=[2, 2, 6, 2]
# cmvit-m: DEPTHS=[1, 1, 10, 1]
# cmvit-v: DEPTHS=[12], DROP_PATH_RATE=0. be default.
# cmvit-base: EMBED_DIM=768, PATCH_SIZE=16, DEPTH=[12], NUM_CLUSTERS=[64]
# c1: NUM_CLUSTERS=[64, 32, 16, 8]
# cN: NUM_CLUSTERS=[64n, 32n, 16n, 8n]
# ppp: POOL_STAGES=[0, 1, 2]
# ppaX: POOL_STAGES=[0, 1], NUM_ASSIGN=[..., ..., X]
# wca: WITH_CLUSTER_ATTN=true
# ctwd: CLUSTER_TOKEN_WD=true
# ncas: WITH_CLUSTER_ATTN_SKIP=False

MODEL:
  TYPE: cmvit
  DROP_PATH_RATE: 0.
  CMVIT:
    EMBED_DIM: 768
    PATCH_SIZE: 16
    DEPTHS: [12]
#    DEPTHS: [2, 2, 6, 2]
#    NUM_CLUSTERS: [512, 256, 128, 1]
    NUM_CLUSTERS: [64]
    WITH_CLUSTER_ATTN: false
    POOL_STAGES: []
    POOL_MODE: unfold
    WITH_GAP: true
    CLUSTER_TOKEN_WD: true
    CLUSTER_MLP_TYPE: [i2c]
    I2C_MLP_RATIO: 0.25
    PATCH_EMBED_TYPE: stem-BN
    WITH_CLUSTER_ATTN_SKIP: false
TRAIN:
  WEIGHT_DECAY: 0.2
